name = "Calum Bird"
description = "Some articles I have published on topics I am passionate about."
license = "MPL 2.0"
homepage = "https://github.com/calum-bird/calum-blog"
# The minimum version of Zola required
min_version = "0.4.0"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Calum Bird"
homepage = "https://calumbird.com"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Nicole White"
homepage = "https://github.com/nicolewhite"
repo = "https://github.com/nicolewhite/nicolewhite.github.io_old"