import Navbar from "@/components/navigation/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="antialiased bg-background text-foreground min-h-dvh">
          <Navbar />
          <div className="max-w-[90ch] mx-auto overflow-x-hidden h-dvh">
            {children}
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
